name: Deploy to npm

on:
  release:
    types: [ published ]

jobs:
  # Run tests first
  test:
    uses: ./.github/workflows/test-and-build.yml
  
  # Deploy to npm only after tests pass
  deploy-npm:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Update package.json version
      run: |
        # Extract version from GitHub release tag
        VERSION=${GITHUB_REF#refs/tags/v}
        npm version --no-git-tag-version $VERSION
    
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publish
